org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official
kotlin.version=2.4.20
compose.version=1.12.1
icons.version=1.7.3
lucene.version=10.5.2
log4j.version=2.26.1
jackson.version=2.22.3
jackson.annotations.version=2.22
jdu.version=4.15
coroutines.version=1.11.0
tokenizers.version=0.38.0
onnx.version=1.22.0
duckdb.version=1.5.5.1
caffeine.version=3.3.0

api.version=1.19.0
core.version=1.23.1
ui.version=1.23.3
app.version=1.7.4
